name: recombination-snakemake
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python
  - bioconda::bcftools
  - pandas
  - cython
  - pytables
  - pip
  - pip:
    - snakemake
    - snakemake-executor-plugin-slurm
    - snakemake-executor-plugin-slurm-jobstep==0.6.0
    - git+https://github.com/gmanthey/ldpop.git
    - git+https://github.com/gmanthey/pyrho.git
